using System.Text.Json.Serialization;
using TwitchSdk.Core;
using TwitchSdk.Helix.Models;

namespace TwitchSdk.Helix;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(HelixPage<TwitchUser>))]
[JsonSerializable(typeof(HelixPage<BlockedUser>))]
[JsonSerializable(typeof(HelixPage<InstalledUserExtension>))]
[JsonSerializable(typeof(UserActiveExtensionsResponse))]
[JsonSerializable(typeof(UpdateUserExtensionsRequest))]
[JsonSerializable(typeof(SendWhisperRequest))]
[JsonSerializable(typeof(ChannelStreamScheduleResponse))]
[JsonSerializable(typeof(CreateScheduleSegmentRequest))]
[JsonSerializable(typeof(UpdateScheduleSegmentRequest))]
[JsonSerializable(typeof(HelixPage<Conduit>))]
[JsonSerializable(typeof(CreateConduitRequest))]
[JsonSerializable(typeof(UpdateConduitRequest))]
[JsonSerializable(typeof(HelixPage<ConduitShard>))]
[JsonSerializable(typeof(UpdateConduitShardsRequest))]
[JsonSerializable(typeof(UpdateConduitShardsResponse))]
[JsonSerializable(typeof(HelixPage<HypeTrainStatus>))]
[JsonSerializable(typeof(HelixPage<TwitchStream>))]
[JsonSerializable(typeof(HelixPage<StreamKeyResult>))]
[JsonSerializable(typeof(CreateStreamMarkerRequest))]
[JsonSerializable(typeof(HelixPage<CreatedStreamMarker>))]
[JsonSerializable(typeof(HelixPage<StreamMarkerGroup>))]
[JsonSerializable(typeof(BroadcasterSubscriptionsResponse))]
[JsonSerializable(typeof(HelixPage<UserSubscription>))]
[JsonSerializable(typeof(BitsLeaderboardResponse))]
[JsonSerializable(typeof(HelixPage<Cheermote>))]
[JsonSerializable(typeof(HelixPage<ExtensionTransaction>))]
[JsonSerializable(typeof(CreateCustomRewardRequest))]
[JsonSerializable(typeof(UpdateCustomRewardRequest))]
[JsonSerializable(typeof(UpdateRedemptionStatusRequest))]
[JsonSerializable(typeof(HelixPage<CustomReward>))]
[JsonSerializable(typeof(HelixPage<CustomRewardRedemption>))]
[JsonSerializable(typeof(CreatePollRequest))]
[JsonSerializable(typeof(EndPollRequest))]
[JsonSerializable(typeof(HelixPage<TwitchPoll>))]
[JsonSerializable(typeof(CreatePredictionRequest))]
[JsonSerializable(typeof(EndPredictionRequest))]
[JsonSerializable(typeof(HelixPage<TwitchPrediction>))]
[JsonSerializable(typeof(HelixPage<ChannelInformation>))]
[JsonSerializable(typeof(ModifyChannelInformationRequest))]
[JsonSerializable(typeof(HelixPage<ChannelEditor>))]
[JsonSerializable(typeof(HelixPage<FollowedChannel>))]
[JsonSerializable(typeof(HelixPage<ChannelFollower>))]
[JsonSerializable(typeof(HelixPage<SendChatMessageResult>))]
[JsonSerializable(typeof(SendChatMessageRequest))]
[JsonSerializable(typeof(CreateEventSubSubscriptionRequest))]
[JsonSerializable(typeof(EventSubSubscriptionsResponse))]
[JsonSerializable(typeof(StartCommercialRequest))]
[JsonSerializable(typeof(HelixPage<CommercialResult>))]
[JsonSerializable(typeof(HelixPage<AdSchedule>))]
[JsonSerializable(typeof(HelixPage<AdSnoozeResult>))]
[JsonSerializable(typeof(HelixPage<ExtensionAnalyticsReport>))]
[JsonSerializable(typeof(HelixPage<GameAnalyticsReport>))]
[JsonSerializable(typeof(HelixPage<TwitchGame>))]
[JsonSerializable(typeof(HelixPage<CategorySearchResult>))]
[JsonSerializable(typeof(HelixPage<ChannelSearchResult>))]
[JsonSerializable(typeof(HelixPage<CreatorGoal>))]
[JsonSerializable(typeof(HelixPage<RaidResult>))]
[JsonSerializable(typeof(HelixPage<CreatedClip>))]
[JsonSerializable(typeof(HelixPage<TwitchClip>))]
[JsonSerializable(typeof(HelixPage<ClipDownload>))]
[JsonSerializable(typeof(HelixPage<TwitchVideo>))]
[JsonSerializable(typeof(HelixPage<string>))]
[JsonSerializable(typeof(HelixPage<CharityCampaign>))]
[JsonSerializable(typeof(HelixPage<CharityDonation>))]
[JsonSerializable(typeof(HelixPage<ChannelTeam>))]
[JsonSerializable(typeof(HelixPage<TwitchTeam>))]
// Each group keeps its own region so parallel additions merge without conflicts.
// <group:moderation-a>
[JsonSerializable(typeof(CheckAutoModStatusRequest))]
[JsonSerializable(typeof(HelixPage<AutoModCheckResult>))]
[JsonSerializable(typeof(ManageHeldAutoModMessageRequest))]
[JsonSerializable(typeof(HelixPage<AutoModSettings>))]
[JsonSerializable(typeof(UpdateAutoModSettingsRequest))]
[JsonSerializable(typeof(HelixPage<BannedUser>))]
[JsonSerializable(typeof(BanUserRequest))]
[JsonSerializable(typeof(HelixPage<BanUserResult>))]
[JsonSerializable(typeof(HelixPage<UnbanRequest>))]
[JsonSerializable(typeof(HelixPage<BlockedTerm>))]
[JsonSerializable(typeof(AddBlockedTermRequest))]
// </group:moderation-a>
// <group:moderation-b>
[JsonSerializable(typeof(HelixPage<ModeratedChannel>))]
[JsonSerializable(typeof(HelixPage<ChannelModerator>))]
[JsonSerializable(typeof(HelixPage<ChannelVip>))]
[JsonSerializable(typeof(UpdateShieldModeStatusRequest))]
[JsonSerializable(typeof(HelixPage<ShieldModeStatus>))]
[JsonSerializable(typeof(WarnChatUserBody))]
[JsonSerializable(typeof(HelixPage<ChatUserWarning>))]
[JsonSerializable(typeof(AddSuspiciousStatusRequest))]
[JsonSerializable(typeof(HelixPage<SuspiciousChatUserStatus>))]
// </group:moderation-b>
// <group:chat-a>
[JsonSerializable(typeof(HelixPage<Chatter>))]
[JsonSerializable(typeof(ChatEmotesResponse<ChannelEmote>))]
[JsonSerializable(typeof(ChatEmotesResponse<GlobalEmote>))]
[JsonSerializable(typeof(ChatEmotesResponse<EmoteSetEmote>))]
[JsonSerializable(typeof(UserEmotesResponse))]
[JsonSerializable(typeof(HelixPage<ChatBadgeSet>))]
[JsonSerializable(typeof(HelixPage<StreamTag>))]
[JsonSerializable(typeof(HelixPage<ContentClassificationLabel>))]
[JsonSerializable(typeof(HelixPage<UserAuthorization>))]
[JsonSerializable(typeof(HelixPage<CustomPowerUp>))]
// </group:chat-a>
// <group:chat-b>
[JsonSerializable(typeof(HelixPage<ChatSettings>))]
[JsonSerializable(typeof(UpdateChatSettingsRequest))]
[JsonSerializable(typeof(SendChatAnnouncementRequest))]
[JsonSerializable(typeof(HelixPage<PinnedChatMessage>))]
[JsonSerializable(typeof(HelixPage<UserChatColor>))]
[JsonSerializable(typeof(HelixPage<SharedChatSession>))]
// </group:chat-b>
// <group:extensions>
[JsonSerializable(typeof(HelixPage<ExtensionConfigurationSegment>))]
[JsonSerializable(typeof(SetExtensionConfigurationSegmentRequest))]
[JsonSerializable(typeof(SetExtensionRequiredConfigurationRequest))]
[JsonSerializable(typeof(SendExtensionPubSubMessageRequest))]
[JsonSerializable(typeof(ExtensionLiveChannelsResponse))]
[JsonSerializable(typeof(HelixPage<ExtensionSecretSet>))]
[JsonSerializable(typeof(SendExtensionChatMessageRequest))]
[JsonSerializable(typeof(HelixPage<TwitchExtension>))]
[JsonSerializable(typeof(HelixPage<ExtensionBitsProduct>))]
[JsonSerializable(typeof(UpdateExtensionBitsProductRequest))]
[JsonSerializable(typeof(HelixPage<DropsEntitlement>))]
[JsonSerializable(typeof(HelixPage<DropsEntitlementUpdate>))]
[JsonSerializable(typeof(UpdateDropsEntitlementsRequest))]
// </group:extensions>
// <group:guest-star>
[JsonSerializable(typeof(HelixPage<GuestStarChannelSettings>))]
[JsonSerializable(typeof(GuestStarUpdateChannelSettingsRequest))]
[JsonSerializable(typeof(HelixPage<GuestStarSession>))]
[JsonSerializable(typeof(HelixPage<GuestStarInvite>))]
// </group:guest-star>
public partial class HelixJsonContext : JsonSerializerContext;
