using System.Text.Json.Serialization;
using TwitchSdk.EventSub.Events;

namespace TwitchSdk.EventSub;

// Each group keeps its own region so parallel additions merge without conflicts.
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(StreamOnlineEvent))]
[JsonSerializable(typeof(StreamOfflineEvent))]
// <group:chat-automod>
[JsonSerializable(typeof(AutomodMessageHoldEvent))]
[JsonSerializable(typeof(AutomodMessageHoldEventV2))]
[JsonSerializable(typeof(AutomodMessageUpdateEvent))]
[JsonSerializable(typeof(AutomodMessageUpdateEventV2))]
[JsonSerializable(typeof(AutomodSettingsUpdateEvent))]
[JsonSerializable(typeof(AutomodTermsUpdateEvent))]
[JsonSerializable(typeof(ChannelChatClearEvent))]
[JsonSerializable(typeof(ChannelChatClearUserMessagesEvent))]
[JsonSerializable(typeof(ChannelChatMessageEvent))]
[JsonSerializable(typeof(ChannelChatMessageDeleteEvent))]
[JsonSerializable(typeof(ChannelChatNotificationEvent))]
[JsonSerializable(typeof(ChannelChatSettingsUpdateEvent))]
[JsonSerializable(typeof(ChannelChatUserMessageHoldEvent))]
[JsonSerializable(typeof(ChannelChatUserMessageUpdateEvent))]
[JsonSerializable(typeof(ChannelSharedChatBeginEvent))]
[JsonSerializable(typeof(ChannelSharedChatUpdateEvent))]
[JsonSerializable(typeof(ChannelSharedChatEndEvent))]
[JsonSerializable(typeof(ChannelSuspiciousUserMessageEvent))]
[JsonSerializable(typeof(ChannelSuspiciousUserUpdateEvent))]
[JsonSerializable(typeof(ChannelWarningAcknowledgeEvent))]
[JsonSerializable(typeof(ChannelWarningSendEvent))]
// </group:chat-automod>
// <group:moderation-channel>
[JsonSerializable(typeof(ChannelUpdateEvent))]
[JsonSerializable(typeof(ChannelFollowEvent))]
[JsonSerializable(typeof(ChannelAdBreakBeginEvent))]
[JsonSerializable(typeof(ChannelRaidEvent))]
[JsonSerializable(typeof(ChannelBanEvent))]
[JsonSerializable(typeof(ChannelUnbanEvent))]
[JsonSerializable(typeof(ChannelUnbanRequestCreateEvent))]
[JsonSerializable(typeof(ChannelUnbanRequestResolveEvent))]
[JsonSerializable(typeof(ChannelModerateEvent))]
[JsonSerializable(typeof(ChannelModerateEventV2))]
[JsonSerializable(typeof(ChannelModeratorAddEvent))]
[JsonSerializable(typeof(ChannelModeratorRemoveEvent))]
[JsonSerializable(typeof(ChannelVipAddEvent))]
[JsonSerializable(typeof(ChannelVipRemoveEvent))]
[JsonSerializable(typeof(ChannelShieldModeBeginEvent))]
[JsonSerializable(typeof(ChannelShieldModeEndEvent))]
[JsonSerializable(typeof(ChannelShoutoutCreateEvent))]
[JsonSerializable(typeof(ChannelShoutoutReceiveEvent))]
// </group:moderation-channel>
// <group:monetization-interaction>
[JsonSerializable(typeof(ChannelBitsUseEvent))]
[JsonSerializable(typeof(ChannelSubscribeEvent))]
[JsonSerializable(typeof(ChannelSubscriptionEndEvent))]
[JsonSerializable(typeof(ChannelSubscriptionGiftEvent))]
[JsonSerializable(typeof(ChannelSubscriptionMessageEvent))]
[JsonSerializable(typeof(ChannelCheerEvent))]
[JsonSerializable(typeof(ChannelPointsAutomaticRewardRedemptionAddEvent))]
[JsonSerializable(typeof(ChannelPointsAutomaticRewardRedemptionAddEventV2))]
[JsonSerializable(typeof(ChannelPointsCustomRewardAddEvent))]
[JsonSerializable(typeof(ChannelPointsCustomRewardUpdateEvent))]
[JsonSerializable(typeof(ChannelPointsCustomRewardRemoveEvent))]
[JsonSerializable(typeof(ChannelPointsCustomRewardRedemptionAddEvent))]
[JsonSerializable(typeof(ChannelPointsCustomRewardRedemptionUpdateEvent))]
[JsonSerializable(typeof(ChannelCustomPowerUpRedemptionAddEvent))]
[JsonSerializable(typeof(ChannelPollBeginEvent))]
[JsonSerializable(typeof(ChannelPollProgressEvent))]
[JsonSerializable(typeof(ChannelPollEndEvent))]
[JsonSerializable(typeof(ChannelPredictionBeginEvent))]
[JsonSerializable(typeof(ChannelPredictionProgressEvent))]
[JsonSerializable(typeof(ChannelPredictionLockEvent))]
[JsonSerializable(typeof(ChannelPredictionEndEvent))]
// </group:monetization-interaction>
// <group:community-system>
[JsonSerializable(typeof(ChannelCharityCampaignDonateEvent))]
[JsonSerializable(typeof(ChannelCharityCampaignStartEvent))]
[JsonSerializable(typeof(ChannelCharityCampaignProgressEvent))]
[JsonSerializable(typeof(ChannelCharityCampaignStopEvent))]
[JsonSerializable(typeof(ChannelGoalBeginEvent))]
[JsonSerializable(typeof(ChannelGoalProgressEvent))]
[JsonSerializable(typeof(ChannelGoalEndEvent))]
[JsonSerializable(typeof(ChannelHypeTrainBeginEvent))]
[JsonSerializable(typeof(ChannelHypeTrainProgressEvent))]
[JsonSerializable(typeof(ChannelHypeTrainEndEvent))]
[JsonSerializable(typeof(UserAuthorizationGrantEvent))]
[JsonSerializable(typeof(UserAuthorizationRevokeEvent))]
[JsonSerializable(typeof(UserUpdateEvent))]
[JsonSerializable(typeof(UserWhisperMessageEvent))]
[JsonSerializable(typeof(ConduitShardDisabledEvent))]
[JsonSerializable(typeof(DropEntitlementGrantEvent))]
[JsonSerializable(typeof(IReadOnlyList<DropEntitlementGrantEvent>))]
[JsonSerializable(typeof(ExtensionBitsTransactionCreateEvent))]
[JsonSerializable(typeof(ChannelGuestStarSessionBeginEvent))]
[JsonSerializable(typeof(ChannelGuestStarSessionEndEvent))]
[JsonSerializable(typeof(ChannelGuestStarGuestUpdateEvent))]
[JsonSerializable(typeof(ChannelGuestStarSettingsUpdateEvent))]
// </group:community-system>
public partial class EventSubEventsJsonContext : JsonSerializerContext;
