<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../TwitchSdk.Authentication/TwitchSdk.Authentication.csproj" />
    <ProjectReference Include="../TwitchSdk.Chat/TwitchSdk.Chat.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
  </ItemGroup>
</Project>
