<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TwitchDock.Authentication/TwitchDock.Authentication.csproj" />
    <ProjectReference Include="../../src/TwitchDock.EventSub/TwitchDock.EventSub.csproj" />
  </ItemGroup>
</Project>
