<#
.SYNOPSIS
Generates docs/coverage.md from the API coverage matrix (docs/api/coverage.json).

.DESCRIPTION
Writes a deterministic Markdown report: summary counts by status and availability for Helix and EventSub, followed by
one table row per Helix endpoint (method and path, status, availability, evidence) and per EventSub type/version.
Works with Windows PowerShell 5.1 and PowerShell 7. Regenerate the report whenever coverage.json changes; do not edit
docs/coverage.md by hand.

.EXAMPLE
powershell -NoProfile -ExecutionPolicy Bypass -File tools/New-CoverageReport.ps1
#>
[CmdletBinding()]
param(
    [string]$InputPath,
    [string]$OutputPath
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
if (-not $InputPath) { $InputPath = Join-Path $root 'docs/api/coverage.json' }
if (-not $OutputPath) { $OutputPath = Join-Path $root 'docs/coverage.md' }

# Read as UTF-8 explicitly: Windows PowerShell 5.1 would otherwise use the ANSI code page.
$matrix = [IO.File]::ReadAllText($InputPath, [Text.Encoding]::UTF8) | ConvertFrom-Json

function Format-Cell([string]$value) {
    if ([string]::IsNullOrEmpty($value)) { return '' }
    return $value.Replace('|', '\|')
}

function Format-Evidence($evidence) {
    $links = foreach ($path in @($evidence)) {
        if ([string]::IsNullOrEmpty($path)) { continue }
        # The report lives in docs/, so repository paths are relative to its parent.
        $target = if ($path.StartsWith('docs/')) { $path.Substring(5) } else { '../' + $path }
        '[{0}]({1})' -f (Split-Path $path -Leaf), $target
    }
    return (@($links) -join ', ')
}

function Format-Counts($items, [string]$property) {
    $groups = @($items | Group-Object -Property $property | Sort-Object -Property @{ Expression = 'Count'; Descending = $true }, @{ Expression = 'Name'; Descending = $false })
    $rows = foreach ($group in $groups) {
        $name = if ([string]::IsNullOrEmpty($group.Name)) { '(none)' } else { $group.Name }
        '| {0} | {1} |' -f (Format-Cell $name), $group.Count
    }
    return @($rows)
}

$helix = @($matrix.helix)
$eventsub = @($matrix.eventsub)
$lines = New-Object 'System.Collections.Generic.List[string]'
$lines.Add('# API coverage')
$lines.Add('')
$lines.Add('> Generated by `tools/New-CoverageReport.ps1` from [`docs/api/coverage.json`](api/coverage.json). Do not edit this file by hand; change the matrix and regenerate it.')
$lines.Add('')
$lines.Add(('Official documentation snapshot: **{0}**. The matrix lists every Helix endpoint and EventSub type/version found in the pinned references below. An entry is `complete` only when its public API, every documented parameter and response field, authorization handling, errors, passing tests and documentation are reviewed; the evidence column links the source, tests and docs. `tools/Test-ApiCoverage.ps1 -RequireComplete` enforces this in CI.' -f $matrix.retrievedOn))
$lines.Add('')
$lines.Add('| Pinned source | SHA-256 |')
$lines.Add('| --- | --- |')
foreach ($source in @($matrix.sources)) { $lines.Add(('| <{0}> | `{1}` |' -f $source.url, $source.sha256)) }
$lines.Add('')
$lines.Add('## Summary')
$lines.Add('')
$lines.Add(('Helix: {0} endpoints. EventSub: {1} subscription type/version pairs. Scopes in the pinned scope table: {2}.' -f $helix.Count, $eventsub.Count, @($matrix.scopes).Count))
$lines.Add('')
foreach ($section in @(
        @{ Title = 'Helix by status'; Items = $helix; Property = 'status' },
        @{ Title = 'Helix by availability'; Items = $helix; Property = 'availabilityReview' },
        @{ Title = 'EventSub by status'; Items = $eventsub; Property = 'status' },
        @{ Title = 'EventSub by availability'; Items = $eventsub; Property = 'availabilityReview' })) {
    $lines.Add(('### {0}' -f $section.Title))
    $lines.Add('')
    $lines.Add('| Value | Count |')
    $lines.Add('| --- | ---: |')
    foreach ($row in (Format-Counts $section.Items $section.Property)) { $lines.Add($row) }
    $lines.Add('')
}
$lines.Add('Availability values: `public` (generally available), `public-beta` (Twitch marks it beta and may change it), `deprecated` (still in the reference but deprecated by Twitch; the SDK marks the methods `[Obsolete]`), and restrictions such as `extension-owner`, `affiliate-or-partner`, `creator-app-and-affiliate-or-partner`, `game-or-organization-owner`, `verified-phone-sender` and `public-with-non-recurring-restrictions`, which describe who may call the API.')
$lines.Add('')
$lines.Add('## Helix endpoints')
$lines.Add('')
$lines.Add('| Endpoint | Method and path | Status | Availability | Evidence |')
$lines.Add('| --- | --- | --- | --- | --- |')
foreach ($item in $helix) {
    $lines.Add(('| [`{0}`]({1}) | `{2} {3}` | {4} | {5} | {6} |' -f $item.id, $item.source, $item.method, $item.path, (Format-Cell $item.status),
            (Format-Cell $item.availabilityReview), (Format-Evidence $item.evidence)))
}
$lines.Add('')
$lines.Add('## EventSub subscription types')
$lines.Add('')
$lines.Add('| Type@version | Status | Availability | Evidence |')
$lines.Add('| --- | --- | --- | --- |')
foreach ($item in $eventsub) {
    $lines.Add(('| [`{0}`]({1}) | {2} | {3} | {4} |' -f $item.id, $item.source, (Format-Cell $item.status), (Format-Cell $item.availabilityReview),
            (Format-Evidence $item.evidence)))
}

# LF line endings and UTF-8 without BOM keep the output identical on Windows PowerShell and PowerShell 7.
$text = ($lines -join "`n") + "`n"
[IO.File]::WriteAllText($OutputPath, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Output ('Wrote {0} (Helix {1}, EventSub {2}).' -f $OutputPath, $helix.Count, $eventsub.Count)
